stamped: false
inputs:
  linear:
    x: axis_r2 - axis_l2
    y: axis_left_y
    z: button_l1 - button_r1
  angular:
    x: -axis_right_x
    y: axis_right_y
    z: axis_left_x
scales:
  linear:
    # Default scale is 1.0
    x: 1
    y: 0.5
    z: 0.1
  angular:
    x: 0.1
    y: 0.1
    z: 1.0
